server:
  port: 9401
spring:
  application:
    name: edu-authentication
#  datasource:
#    #数据源基本配置
#    type: com.alibaba.druid.pool.DruidDataSource
#    url: jdbc:mysql://139.129.101.91:3306/OES?serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
#    #    url: jdbc:mysql://192.168.1.149:3306/edu_organization?serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
#    username: root
#    password: Xkj_13011301
#    #    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  redis:
#    database: 0
#    port: 8085
#    host: 139.129.101.91
#    password: Xkj_13011301
#    timeout: 2000



eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #实例名
    prefer-ip-address: true  #是否使用IP地址注册
#  client:
#    #表示是否将自己注册进EurekaServer 默认为true
#    register-with-eureka: true
#    # 是否从EurekaServer抓取已有的注册信息，默认为true.单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
#    feth-registry: true
#    serviceUrl:
#      defaultZone: http://localhost:7001/eureka
##      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka #集群版


mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml