server:
  port: 8003

spring:
  application:
    name: edu-service-course
  datasource:
    #数据源基本配置
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://139.129.101.91:3306/OES?serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true&allowMultiQueries=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: Xkj_13011301
    driver-class-name: com.mysql.cj.jdbc.Driver
  # redis配置
  redis:
    database: 0
    host: 139.129.101.91
    port: 8085
    password: Xkj_13011301
    timeout: 2000
    lettuce:
      pool:
        max-active: 8
        max-wait: 5000ms
        max-idle: 8
        min-idle: 0

eureka:
  client:
    #表示是否将自己注册进EurekaServer 默认为true
    register-with-eureka: true
    # 是否从EurekaServer抓取已有的注册信息，默认为true.单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    feth-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
  #      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka #集群版
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #实例名
    prefer-ip-address: true  #是否使用IP地址注册

# mybatis 配置信息
mybatis:
  mapper-locations: classpath:mapper/*.xml
#  config-location: classpath:mybatis/mybatis-config.xml

# 日志输出
logging:
  level:
    com.oes.core: debug
  pattern:
    rolling-file-name: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.log