server:
  port: 8010

spring:
  application:
    name: edu-service-payment
  profiles:
    active: common
  datasource:
    #数据源基本配置
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://139.129.101.91:3306/OES?serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true&allowMultiQueries=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: Xkj_13011301
    driver-class-name: com.mysql.cj.jdbc.Driver
  # redis配置
  redis:
    database: 0
    host: 139.129.101.91
    port: 8085
    password: Xkj_13011301
    timeout: 2000
    lettuce:
      pool:
        max-active: 8
        max-wait: 5000ms
        max-idle: 8
        min-idle: 0

eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #实例名
    prefer-ip-address: true  #是否使用IP地址注册

# mybatis 配置信息
mybatis:
  mapper-locations: classpath:mapper/*.xml

