server:
  port: 9527

spring:
  application:
    name: edu-service-gateway
  cloud:
    gateway:
#      routes:
#        - id: service-user  #payment_routh    #路由的ID，没有固定规则但要求唯一，简易配合服务名
#          uri: http://SERVICE-USERCENTER         #匹配后提供服务的路由地址
#          predicates:
#            - Path=/user/*          #断言，路径相匹配的进行路由
      routes:
        - id: route-simple  #payment_routh    #路由的ID，没有固定规则但要求唯一，简易配合服务名
          uri: http://localhost:8001         #匹配后提供服务的路由地址
          predicates:
            - Path=/user/**          #断言，路径相匹配的进行路由



eureka:
  instance:
    hostname: edu-gateway
  client:
    #表示是否将自己注册进EurekaServer 默认为true
    register-with-eureka: true
    # 是否从EurekaServer抓取已有的注册信息，默认为true.单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    feth-registry: true
    serviceUrl:
      defaultZone: http://localhost:7001/eureka
#      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka #集群版
